version: '3.3'
services:
  geoexmap:
    image: sc-registry.fredhutch.org/geoexmap:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.geoexmap.rule=Host(`geoexmap.fredhutch.org`)"
        - "traefik.http.routers.geoexmap-secured.rule=Host(`geoexmap.fredhutch.org`)"
        - "traefik.http.routers.geoexmap.entrypoints=web,web-secured"
        - "traefik.http.services.geoexmap.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.geoexmap.tls=true"

networks:
  sc-swarm-net:
    external: true